### PR TITLE
Add examples and documentation to README

### PR DESCRIPTION
**Pull request by danthegoodman**
I'm in the process of learning how to work with the scribe editor, so I wrote some documentation based on my findings. 

Hopefully it will help others get up to speed a little faster when using this plugin.

### CODE REVIEW

**Comment by rrees** [comment]
Thanks very much for contributing!

I think some of this might be better in the repo's wiki rather than README. I'll try and make a start on this as soon as I can and I'll comment back on this PR when I have something.

**Comment by rrees** [comment]
Do you want to take a look at what I've put on the [wiki](https://github.com/guardian/scribe-plugin-toolbar/wiki) would this have been enough to help you?

**Comment by danthegoodman** [comment]
This is great! Thank you.

I would not intuitively look at the Wiki. How do you feel about updating the README with a note to look at the Wiki for more information?

**Comment by rrees** [comment]
Makes sense, I'll do it soon

**Comment by rrees** [comment]
Done!

**Comment by danthegoodman** [comment]
Great! Thank you :+1:

**Pull request closed without merging**
