### PR TITLE
Allow single toolbar to be used across multiple scribe editors. 

### PR DESCRIPTION
**Pull request by shihabuddin**
Fixes guardian/scribe#69

### CODE REVIEW

**Comment by hmgibson23** [comment]
Seems fine @rrees - any thoughts?

**Comment by theefer** [comment]
What's the impact on stateful commands such as Undo/Redo?

**Comment by rrees** [comment]
@shihabuddin Could you add an example file so it is easy to check the behaviour of Scribe in the circumstances you imagine this feature would be used?

**Comment by shihabuddin** [comment]
@rrees Please see [this repo](https://github.com/shihabuddin/scribe-toolbar-multiple-example)

**Comment by rrees** [comment]
@shihabuddin Thanks I will take a look as soon as I have time

**Comment by bedeoverend** [comment]
+1

**Comment by hamnis** [comment]
Any progress with this?

**Comment by rrees** [comment]
I need to look at the example file and test what happens with Undo/Redo and how this works with the internal Guardian products that use multiple Scribe instances. Sorry we can't go faster on this.

**Comment by hamnis** [comment]
I dont suppose there is any progress here?

**Comment by rrees** [comment]
It is relatively low priority but I will try and do the testing before the end of the year.

**Comment by rrees** [comment]
Implemented in #21

**Pull request closed without merging**
