### PR TITLE
Remove button selector

### PR DESCRIPTION
**Pull request by samvasko**
I think there is no significant gain from specifying node name there.

### CODE REVIEW

**Comment by shaunnetherby** [comment]
@OliverJAsh When is the next release for this? I'd like to use non-buttons as well.

**Comment by OliverJAsh** [comment]
It should be out by now! @shaunnetherby

**Comment by shaunnetherby** [comment]
@OliverJAsh I noticed its merged into master but its not in the dist branch - was it merged but never released?  When I bower install I still have the 'button' specifier in there.  Unless I'm just missing something?

**Comment by rrees** [comment]
There doesn't appear to be a bower release with this so I'm happy to put one together later and update the release

**Comment by shaunnetherby** [comment]
@rrees That would be awesome

**Comment by rrees** [comment]
Hi there, v0.1.5 is out which should have this change

**Pull request merged**
